server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: gbmysql-568028827227
    url: jdbc:mysql://47.110.240.241:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
